function infobox(~,~)
% Infobox für Bedienung der Aufbereitung2.m GUI
%
% Version: 1.0
% Datum: 2017-04-06
% Autor: Peter Jüstel
% Lizenz: CC-BY-SA 4.0 (Feel free, but attribute the author, and share remixes under similar terms)
% https://creativecommons.org/licenses/by-sa/4.0/
% https://creativecommons.org/licenses/by-sa/4.0/legalcode


figure('units','normalized',...
		'Position',[0.75 0.18 0.25 0.72],... % Position: [left bottom width heights]
		'NumberTitle', 'off',...			% Schaltet "Figure n" im Fenstertitel ab.
		'Name', 'Info',...
		'Color','w');


Text = {'Bedienung:','','Bewegen: Achsenfläche ziehen','Zoomen: Mausrad','Nur X-/Y-Zoom: Shift/Strg', 'Neues Intervall: an zwei Stellen auf den Plot clicken','Intervall löschen: auf die Zahl des Intervalls clicken', 'Intervall Grenze bewegen: drag&drop','"Grenzen Versuch(vnum)" Intervall legt die X-Achsenlimits für den Versuch fest','','','', ...
					'Speichern der Änderungen:', '', 'Alle Änderungen werden in der figure zwischengespeichert, und bleiben erhalten, wenn man den Intervalltyp wechselt. Die Änderungen werden aber erst in der Ergebnis Datei abgespeichert, wenn der "Speichern" Knopf gedrückt wird. Dies ermöglicht es, Änderungen zu verwerfen, indem man das Fenster schließt.','Es werden automatisch Backups von der Ergebnisdatei erzeugt. Für jeden Tag wird ein Backup angelegt, welches immer überschrieben wird.','','','', ...
					'"Flut" Knopf:','','Führt den Flutungsalgorithmus auf die Versuchsdaten aus. Bei geeignet glatten Daten, werden die stationären zustände automatisch erkannt, und den Clustern hinzugefügt.','','','',...
					'Filter:','','0: Filterkurve ausblenden','1: Zentraler Mittelwert', '2: Zentraler Median', '3: Mit Vertikal-abstand gewichteter Mittelwert'};


uicontrol('Style', 'text',...
        'String',Text,...
        'units','normalized',...
        'BackgroundColor',[0.96 0.96 0.96],...
        'FontSize',11,...
		'HorizontalAlignment', 'left',...
        'Position', [0.03 0.02 0.94 0.96]);

% assignin('base', 'infofigure', infofigure)